### ISSUE TITLE
Use NuGet.exe exclusively

### ISSUE THREAD

**Issue by adamralph** [adamralph/bau-nuget#8]
We shouldn't be using NuGet.Core for some things and NuGet.exe for others. We should be using one or the other. I'm preferring NuGet.exe so that at some point we can allow flexibility with the target and people can use their own installations on PATH, etc.

**Comment by adamralph** [comment]
Given that this is ahead of the initial release, I think it's just a refactoring.

**Comment by aarondandy** [comment]
It would be my pleasure! Additionally it should be pretty easy to add in a property that could be used to override the NuGet.exe default search behavior. There may be value in having the NuGet.Core reference later so that it can be used to "install" NuGet.exe somewhere but we can wait until then to add it back on.

**Comment by aarondandy** [comment]
NuGet.Core is gone
